#!/bin/sh

#################################################################################
#
# SSH
#
#################################################################################
#
# Path to ssh config files


#
#################################################################################
#
    InsertSection "SSH"

    # Test        : SSH-000
    # Description : Check if ssh is being used
    Register --test-no DBS-1804 --weight L --network NO --category security --description "Checking active ssh daemon"
    if [ ${SKIPTEST} -eq 0 ]; then
        FIND=$(${PSBINARY} ax | ${EGREPBINARY} "ssh" | ${GREPBINARY} -v "grep")
        if [ -z "${FIND}" ]; then
            SSH_RUNNING=0
            Display --indent 2 --text "- SSH process status" --result "${STATUS_NOT_FOUND}" --color GREEN
            LogText "Result: SSH process not active"
        else
            Display --indent 2 --text "- SSH process status" --result "${STATUS_FOUND}" --color GREEN
            LogText "Result: SSH is active"
            SSH_RUNNING=1
            Report "SSH_service=${SSH_RUNNING}"
        fi
    fi
#
#################################################################################
#
    # Test        : SSH-0001
    # Description : Ensure SSH root login is disabled
    # Reference   : https://www.tenable.com/audits/items/CIS_Ubuntu_22.04_LTS_v1.0.0_Server_L1.audit:13f14fcee36064a2ef722bb4d40f20d7

    if [ ${SSH_RUNNING} -eq 1 ]; then PREQS_MET="YES"; SKIPREASON=""; else PREQS_MET="NO"; SKIPREASON="SSH not installed, or not running"; fi
    Register --test-no SSH-0001 --preqs-met ${PREQS_MET} --skip-reason "${SKIPREASON}" --weight L --network NO --category security --description "Ensure SSH root login is disabled"
    if [ ${SKIPTEST} -eq 0 ]; then
        SSH_ROOT=$(grep "^\s*PermitRootLogin no\s*$" /etc/ssh/sshd_config)
        if [ -z "$SSH_ROOT" ];then
            Display --indent 2 --text "- SSH root login enabled" --result "${STATUS_ERROR}" --color RED
        else
            Display --indent 2 --text "- SSH root login disabled" --result "${STATUS_OK}" --color GREEN
        fi
    fi

#
#################################################################################
#
    # Test        : SSH-0002
    # Description : Ensure SSH AllowTcpForwarding is disabled
    # Reference   : https://www.tenable.com/audits/items/CIS_Distribution_Independent_Linux_Server_L2_v2.0.0.audit:442b5a19a23bed7f8ac3fff5a9c41c01
    
    if [ ${SSH_RUNNING} -eq 1 ]; then PREQS_MET="YES"; SKIPREASON=""; else PREQS_MET="NO"; SKIPREASON="SSH not installed, or not running"; fi
    Register --test-no SSH-0002 --preqs-met ${PREQS_MET} --skip-reason "${SKIPREASON}" --weight L --network NO --category security --description "Ensure SSH AllowTcpForwarding is disabled"
    if [ ${SKIPTEST} -eq 0 ]; then
        ALLOW_TCP=$(grep "^\s*AllowTcpForwarding no\s*$" /etc/ssh/sshd_config)
        if [ -z "$ALLOW_TCP" ];then
            Display --indent 2 --text "- AllowTcpForwarding enabled" --result "${STATUS_ERROR}" --color RED
        else
            Display --indent 2 --text "- AllowTcpForwarding disabled" --result "${STATUS_OK}" --color GREEN
        fi 
    fi
#
#################################################################################
#
    # Test        : SSH-0003
    # Description : Ensure SSH LogLevel is appropriate
    # Reference   : https://www.tenable.com/audits/items/CIS_Distribution_Independent_Linux_Workstation_L1_v2.0.0.audit:3ecd05898c9b54268f3e9533895ec1ca
    
    if [ ${SSH_RUNNING} -eq 1 ]; then PREQS_MET="YES"; SKIPREASON=""; else PREQS_MET="NO"; SKIPREASON="SSH not installed, or not running"; fi
    Register --test-no SSH-0003 --preqs-met ${PREQS_MET} --skip-reason "${SKIPREASON}" --weight L --network NO --category security --description "Ensure SSH LogLevel is appropriate"
    if [ ${SKIPTEST} -eq 0 ]; then
        LOG_LEVEL=$(grep "^\s*LogLevel VERBOSE\s*$" /etc/ssh/sshd_config)
        if [ -z "$LOG_LEVEL" ];then
            Display --indent 2 --text "- LogLevel not set to VERBOSE" --result "${STATUS_ERROR}" --color RED
        else
            Display --indent 2 --text "- LogLevel set to VERBOSE" --result "${STATUS_OK}" --color GREEN
        fi 
    fi
#
#################################################################################
#

WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
