#!/bin/sh

#################################################################################
#
# General Linux Hardening
#
#################################################################################
# Linux Configuration files


#
#################################################################################
#
    InsertSection "General Linux Hardening"

    # Test        : Linux-0001
    # Description : Ensure permissions on /etc/passwd are configured
    # Reference   : https://www.tenable.com/audits/items/CIS_Distribution_Independent_Linux_Workstation_L1_v2.0.0.audit:a6fa37cc8c6fc0acb6b4d7a7c0093600

    Register --test-no Linux-0000 --weight L --network NO --category security --description "Ensure permissions on /etc/passwd are configured"
    if [ ${SKIPTEST} -eq 0 ]; then
        PERMISSIONS=$(stat -c "%a" /etc/passwd)
        if [ "$PERMISSIONS" = "644" ]; then
            Display --indent 2 --text "- /etc/passwd permissions" --result "${STATUS_OK}" --color GREEN
        else
            Display --indent 2 --text "- /etc/passwd permissions" --result "${STATUS_ERROR}" --color RED
        fi
    fi
#
#################################################################################
#
    # Test        : Linux-0002
    # Description : Ensure password expiration is 365 days or less - users
    # Reference   : https://www.tenable.com/audits/items/CIS_Distribution_Independent_Linux_Server_L1_v2.0.0.audit:fb990c884c55137c49ef5d656ed87bfe

    Register --test-no Linux-0002 --weight L --network NO --category security --description "Ensure password expiration is 365 days or less"
    if [ ${SKIPTEST} -eq 0 ]; then
        MAX_DAYS=$(grep "^ *PASS_MAX_DAYS" /etc/login.defs | awk '{print $2}')
        if [ $MAX_DAYS -lt "365" ];then
            Display --indent 2 --text "- Ensure password expiration is 365 days or less" --result "${STATUS_OK}" --color GREEN
        else
            Display --indent 2 --text "- Ensure password expiration is 365 days or less" --result "${STATUS_ERROR}" --color RED
        fi
    fi
#
#################################################################################
#
    # Test        : Linux-0003
    # Description : Ensure there is a firewall running and blocking all ports except 22 and 443
    Register --test-no Linux-0003 --weight L --network NO --category security --description "Ensure there is a firewall running"
    if [ ${SKIPTEST} -eq 0 ]; then
        FIREWALL=$(ufw status)
        if [ $? -eq 127 ];then
            Display --indent 2 --text "- UFW not installed" --result "${STATUS_ERROR}" --color RED
        else
            FIREWALL_ENABLED=$(ufw status)
            if [ "$FIREWALL_ENABLED" = "Status: inactive" ];then
                Display --indent 2 --text "- Firewall disabled" --result "${STATUS_ERROR}" --color RED
            else
                FIREWALL_OPENPORTS=$(ufw status | grep ALLOW | cut -d " " -f1-2 | grep -v "v6" | uniq )
                DISALLOWED_PORT=0
                for i in $FIREWALL_OPENPORTS; do 
                    if [ $i != "443" -a $i != "22" ];then
                        Display --indent 2 --text "- Allowed $i port " --result "${STATUS_ERROR}" --color RED
                        DISALLOWED_PORT=1
                    fi
                done
                if [ $i -eq 0 ];then
                    Display --indent 2 --text "- Firewall enabled and correctly configured" --result "${STATUS_OK}" --color GREEN
                fi
            fi
        fi
    fi
#
#################################################################################
#

WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
