#!/bin/sh

#################################################################################
#
# Apache
#
#################################################################################
#
# Paths to Apache configuration files

#
#################################################################################
#
    InsertSection "Apache"

    # Test        : APACHE-000
    # Description : Check if Postgresql is being used
    Register --test-no APACHE-000 --weight L --network NO --category security --description "Checking active Apache process"
    if [ ${SKIPTEST} -eq 0 ]; then
        FIND=$(${PSBINARY} ax | ${EGREPBINARY} "apache" | ${GREPBINARY} -v "grep")
        if [ -z "${FIND}" ]; then
            Display --indent 2 --text "- Apache process status" --result "${STATUS_NOT_FOUND}" --color GREEN 
            LogText "Result: Apache process not active"
        else
            Display --indent 2 --text "- Apache process status" --result "${STATUS_FOUND}" --color GREEN
             LogText "Result: Apache is active"
             APACHE_RUNNING=1
             DATABASE_ENGINE_RUNNING=1
             Report "Apache_running=${APACHE_RUNNING}"
        fi
    fi
#
#################################################################################
#
    # Test        : APACHE-0001
    # Description : Ensure the Apache Web Server Runs As a Non-Root user and group -> rootuser, rootuser
    # Reference   : https://www.tenable.com/audits/items/CIS_Apache_HTTP_Server_2.2_Benchmark_v3.6.0_Level_1_Middleware.audit:da4527cf054249af376de28646549e1b

    Register --test-no APACHE-0001 --weight L --network NO --category security --description "Checking Apache Web Server Runs As a Non-Root user and group"
    if [ ${SKIPTEST} -eq 0 ]; then
        APACHE_USER=$(grep "^\s*User\s*www-data\s*$" /etc/apache2/apache2.conf)
        APACHE_GROUP=$(grep "^\s*Group\s*www-data\s*$" /etc/apache2/apache2.conf)
        if [ ! -z "$APACHE_USER" ] && [ ! -z "$APACHE_GROUP" ];then
            Display --indent 2 --text "- Apache runs as a Non-Root user and group" --result "${STATUS_OK}" --color GREEN
        else
            Display --indent 2 --text "- Apache does not run as a Non-Root user and group" --result "${STATUS_ERROR}" --color RED
        fi

    fi
#
#################################################################################
#
    # Test        : APACHE-0002
    # Description : Ensure Weak SSL Protocols Are Disabled (SSLv2, SSLv3 and TLSv1) -> TLSv1
    # Reference   : https://www.tenable.com/audits/items/CIS_Apache_HTTP_Server_2.2_Benchmark_v3.6.0_Level_1.audit:2c18b98397ec1e28989b6e6a4e12db2e

    Register --test-no APACHE-0002 --weight L --network NO --category security --description "Checking Weak SSL Protocols Are Disabled"
    if [ ${SKIPTEST} -eq 0 ]; then
        PROTOCOL=$(grep "^\s*SSLProtocol\s*-all\s*+TLSv1.2\s*$" /etc/apache2/mods-enabled/ssl.conf)
        if [ ! -z "$PROTOCOL" ];then
            Display --indent 2 --text "- Weak SSL Protocols Are Disabled" --result "${STATUS_OK}" --color GREEN
        else 
            Display --indent 2 --text "- Weak SSL Protocols Are Enabled" --result "${STATUS_ERROR}" --color RED
        fi
    fi
#
#################################################################################
#
    # Test        : APACHE-0003
    # Description : Ensure MaxKeepAliveRequests is Set to a Value of 100 or Greater
    # Reference   : https://www.tenable.com/audits/items/CIS_Apache_HTTP_Server_2.4_Benchmark_v2.0.0_Level_1_Middleware.audit:a90ce8542eda0476fc0ccee6b54b5532

    Register --test-no APACHE-0003 --weight L --network NO --category security --description "Checking KeepAliveTimeout for apache2 configuration"
    if [ ${SKIPTEST} -eq 0 ]; then
        KEEP_ALIVE=$(grep "^\s*KeepAliveTimeout" /etc/apache2/apache2.conf  | cut -d " " -f2 )
        if [ $KEEP_ALIVE -lt "16" ];then
            Display --indent 2 --text "- KeepAliveTimeout is set to a value of 15 or less" --result "${STATUS_OK}" --color GREEN
        else 
            Display --indent 2 --text "- KeepAliveTimeout is not set to a value of 15 or less" --result "${STATUS_ERROR}" --color RED
        fi
    fi


#
#################################################################################
#

WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
