#!/bin/sh

#################################################################################
#
# General Linux Hardening
#
#################################################################################
# Linux Configuration files


#
#################################################################################
#
    InsertSection "General Linux Hardening"

    # Test        : DBS-1804
    # Description : Check if MySQL is being used
    Register --test-no DBS-1804 --weight L --network NO --category security --description "Checking active MySQL process"
    if [ ${SKIPTEST} -eq 0 ]; then
    #     FIND=$(${PSBINARY} ax | ${EGREPBINARY} "mariadb|mysqld|mysqld_safe" | ${GREPBINARY} -v "grep")
    #     if [ -z "${FIND}" ]; then
    #         if [ ${DEBUG} -eq 1 ]; then Display --indent 2 --text "- MySQL process status" --result "${STATUS_NOT_FOUND}" --color WHITE --debug; fi
    #         LogText "Result: MySQL process not active"
    #     else
    #         Display --indent 2 --text "- MySQL process status" --result "${STATUS_FOUND}" --color GREEN
    #         LogText "Result: MySQL is active"
    #         MYSQL_RUNNING=1
    #         DATABASE_ENGINE_RUNNING=1
    #         Report "mysql_running=${MYSQL_RUNNING}"
    #     fi
    fi
#
#################################################################################
#
    if [ ${DATABASE_ENGINE_RUNNING} -eq 0 ]; then
        Display --indent 4 --text "No database engines found"
    fi
#
#################################################################################
#

WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
