  - name: Ensure the Apache Web Server Runs As a Non-Root user and group
    lineinfile:
      path: /etc/apache2/apache2.conf
      state: present
      regexp: '^User'
      line: 'User www-data'
  
  - name: Ensure the Apache Web Server Runs As a Non-Root user and group
  # CODE


  - name: Ensure Weak SSL Protocols Are Disabled (SSLv2, SSLv3 and TLSv1) 
  # CODE


  - name: Ensure MaxKeepAliveRequests is Set to a Value of 100 or Greater
  # CODE

  - name: Apply apache changes
    ansible.builtin.service:
      name: apache2
      state: restarted
