  - name: Correct permissions on /etc/passwd (644)
    ansible.builtin.file:
      path: /etc/passwd
      owner: root
      group: root
      mode: '0644'

  - name: Ensure password expiration 
    lineinfile:
      path: /etc/login.defs
      state: present
      regexp: '^PASS_MAX_DAYS'
      line: 'PASS_MAX_DAYS 365'


  - name: Reset firewall
    community.general.ufw:
      state: reset

  - name: Start UFW
    community.general.ufw:
      state: enabled

  - name: Open port 22
    community.general.ufw:
      rule: allow
      port: '22'
      proto: tcp

  - name: Open port 443
    community.general.ufw:
      rule: allow
      port: '443'
      proto: tcp