  - name: Correct permissions on /etc/passwd (644)
    ansible.builtin.file:
      path: /etc/passwd
      owner: root
      group: root
      mode: '0644'

  - name: Ensure password expiration and /etc/passwd permissions
    # CODE


  - name: Reset firewall
    community.general.ufw:
      state: reset

  - name: Start UFW
    community.general.ufw:
      state: enabled

  - name: Open port 22
    # CODE


  - name: Open port 443
    # CODE
