  - name: Ensure SSH root login is disabled
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^PermitRootLogin'
      line: 'PermitRootLogin no'
  
  - name: Ensure SSH AllowTcpForwarding is disabled
    # CODE


  - name: Ensure SSH LogLevel is appropriate
    # CODE


  - name: Apply ssh changes
    ansible.builtin.service:
      name: sshd
      state: restarted