---
- hosts: all
  become: yes

  tasks:
   - name: Hardening Linux
     ansible.builtin.import_tasks:
       file: hardeningScripts/linux.yml

   - name: Hardening SSH
     ansible.builtin.import_tasks:
       file: hardeningScripts/ssh.yml

   - name: Hardening Apache
     ansible.builtin.import_tasks:
       file: hardeningScripts/apache.yml
